packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  sharp: true
  unrs-resolver: true
  msw: false
  esbuild: true
  lefthook: true
  workerd: true
  '@swc/core': true
  mongodb-memory-server: true

minimumReleaseAgeExclude:
  - tinyexec@1.3.0
  - '@payloadcms/db-mongodb@3.87.1'
  - '@payloadcms/graphql@3.87.1'
  - '@payloadcms/next@3.87.1'
  - '@payloadcms/richtext-lexical@3.87.1'
  - '@payloadcms/translations@3.87.1'
  - '@payloadcms/ui@3.87.1'
  - payload@3.87.1
